# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wipro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Wipro

  # Network Service
  pod 'Alamofire', '~> 4.9.1'

  # Image Downlaod and Caching
  pod 'Kingfisher'
  
  # Empty Data View
  pod 'EmptyDataSet-Swift'
  
  # Snackbar to show success or fail Messages
  pod 'SwiftMessages', '6.0.0'

  target 'WiproTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.9.1'
    pod 'Kingfisher'
  end

end
